"""add_rsvp_invites_email_prefs

Revision ID: a7293ca816f9
Revises: b22d6e1ac665
Create Date: 2026-06-28 22:12:34.609939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a7293ca816f9'
down_revision: Union[str, Sequence[str], None] = 'b22d6e1ac665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'parent', 'teacher', name='userrole', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('email_grades', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('email_announcements', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('email_events', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_events')
    op.drop_column('users', 'email_announcements')
    op.drop_column('users', 'email_grades')
    op.drop_table('event_registrations')
    op.drop_table('invites')
    # ### end Alembic commands ###
