"""add_event_time_and_image_urls

Revision ID: b22d6e1ac665
Revises: d4e5f6a7b8c9
Create Date: 2026-06-28 21:28:15.684878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22d6e1ac665'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('event_timezone', sa.String(length=64), nullable=True))
    op.add_column('events', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'event_timezone')
    op.drop_column('events', 'event_time')
    # ### end Alembic commands ###
